"""empty message

Revision ID: e968c10d3931
Revises: 
Create Date: 2025-08-19 17:20:20.375486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e968c10d3931'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_key', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('webhook_url', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('webhook_url')
        batch_op.drop_column('api_key')

    # ### end Alembic commands ###
